name: Run Zero to Nix site tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    environment: test
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Restore Lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: lychee-link-check
          restore-keys: cache-lychee-
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Nix CI suite
        run: nix develop --command ci
      - name: Check external links
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            --cache
            --verbose
            --no-progress
            ./dist
          fail: true
      - name: Check flake templates
        run: ./scripts/check-flake-templates.sh
